-- MySQL Script generated by MySQL Workbench
-- 11/17/19 15:15:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id11622579_mybook_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id11622579_mybook_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id11622579_mybook_db` DEFAULT CHARACTER SET utf8 ;
USE `id11622579_mybook_db` ;

-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`korisnik` (
  `kor_ime` VARCHAR(20) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `lozinka` TEXT NOT NULL,
  `datum_rodenja` DATE NOT NULL,
  PRIMARY KEY (`kor_ime`),
  UNIQUE INDEX `kor_ime_UNIQUE` (`kor_ime` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`izdavac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`izdavac` (
  `id_izdavac` INT NOT NULL,
  `ime_izdavaca` VARCHAR(100) NOT NULL,
  `mjesto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_izdavac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`knjiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`knjiga` (
  `id_knjiga` INT NOT NULL,
  `naziv` VARCHAR(60) NOT NULL,
  `godina_izdavanja` YEAR NOT NULL,
  `url` VARCHAR(45) NULL,
  `slika_naslovnice` BLOB NULL,
  `sazetak` VARCHAR(255) NULL,
  `izdavac_id_izdavac` INT NOT NULL,
  PRIMARY KEY (`id_knjiga`),
  INDEX `fk_Knjiga_Izdavac1_idx` (`izdavac_id_izdavac` ASC),
  CONSTRAINT `fk_Knjiga_Izdavac1`
    FOREIGN KEY (`izdavac_id_izdavac`)
    REFERENCES `id11622579_mybook_db`.`izdavac` (`id_izdavac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`favoriti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`favoriti` (
  `korisnik_kor_ime` VARCHAR(20) NOT NULL,
  `knjiga_id_knjiga` INT NOT NULL,
  PRIMARY KEY (`korisnik_kor_ime`, `knjiga_id_knjiga`),
  INDEX `fk_Favoriti_Korisnik1_idx` (`korisnik_kor_ime` ASC),
  INDEX `fk_Favoriti_Knjiga1_idx` (`knjiga_id_knjiga` ASC),
  CONSTRAINT `fk_Favoriti_Korisnik1`
    FOREIGN KEY (`korisnik_kor_ime`)
    REFERENCES `id11622579_mybook_db`.`korisnik` (`kor_ime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favoriti_Knjiga1`
    FOREIGN KEY (`knjiga_id_knjiga`)
    REFERENCES `id11622579_mybook_db`.`knjiga` (`id_knjiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`statistika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`statistika` (
  `korisnik_kor_ime` VARCHAR(20) NOT NULL,
  `knjiga_id_knjiga` INT NOT NULL,
  `datum` DATE NOT NULL,
  `ocjena` INT NOT NULL,
  `komentar` LONGTEXT NOT NULL,
  PRIMARY KEY (`korisnik_kor_ime`, `knjiga_id_knjiga`),
  INDEX `fk_Statistika_Korisnik1_idx` (`korisnik_kor_ime` ASC),
  INDEX `fk_Statistika_Knjiga1_idx` (`knjiga_id_knjiga` ASC),
  CONSTRAINT `fk_Statistika_Korisnik1`
    FOREIGN KEY (`korisnik_kor_ime`)
    REFERENCES `id11622579_mybook_db`.`korisnik` (`kor_ime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statistika_Knjiga1`
    FOREIGN KEY (`knjiga_id_knjiga`)
    REFERENCES `id11622579_mybook_db`.`knjiga` (`id_knjiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`znacka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`znacka` (
  `id_znacka` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `uvijet` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_znacka`),
  UNIQUE INDEX `naziv_UNIQUE` (`naziv` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`osvojena_znacka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`osvojena_znacka` (
  `korisnik_kor_ime` VARCHAR(20) NOT NULL,
  `znacka_id_znacka` INT NOT NULL,
  `datum` DATE NOT NULL,
  PRIMARY KEY (`korisnik_kor_ime`, `znacka_id_znacka`),
  INDEX `fk_Osvojena_znacka_Korisnik1_idx` (`korisnik_kor_ime` ASC),
  INDEX `fk_Osvojena_znacka_Znacka1_idx` (`znacka_id_znacka` ASC),
  CONSTRAINT `fk_Osvojena_znacka_Korisnik1`
    FOREIGN KEY (`korisnik_kor_ime`)
    REFERENCES `id11622579_mybook_db`.`korisnik` (`kor_ime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Osvojena_znacka_Znacka1`
    FOREIGN KEY (`znacka_id_znacka`)
    REFERENCES `id11622579_mybook_db`.`znacka` (`id_znacka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`autor` (
  `id_autor` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `datum_rodenja` DATE NOT NULL,
  `o_autoru` LONGTEXT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`zanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`zanr` (
  `id_zanr` INT NOT NULL,
  `naziv` VARCHAR(100) NOT NULL,
  `opis` LONGTEXT NULL,
  PRIMARY KEY (`id_zanr`),
  UNIQUE INDEX `Naziv_UNIQUE` (`naziv` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`interesi_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`interesi_korisnika` (
  `korisnik_kor_ime` VARCHAR(20) NOT NULL,
  `autor_id_autor` INT NOT NULL,
  `zanr_id_zanr` INT NOT NULL,
  PRIMARY KEY (`korisnik_kor_ime`, `autor_id_autor`, `zanr_id_zanr`),
  INDEX `fk_Interesi_korisnika_Autor1_idx` (`autor_id_autor` ASC),
  INDEX `fk_Interesi_korisnika_Zanr1_idx` (`zanr_id_zanr` ASC),
  CONSTRAINT `fk_Interesi_korisnika_Korisnik1`
    FOREIGN KEY (`korisnik_kor_ime`)
    REFERENCES `id11622579_mybook_db`.`korisnik` (`kor_ime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interesi_korisnika_Autor1`
    FOREIGN KEY (`autor_id_autor`)
    REFERENCES `id11622579_mybook_db`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interesi_korisnika_Zanr1`
    FOREIGN KEY (`zanr_id_zanr`)
    REFERENCES `id11622579_mybook_db`.`zanr` (`id_zanr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`autor_knjige`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`autor_knjige` (
  `knjiga_id_knjiga` INT NOT NULL,
  `autor_id_autor` INT NOT NULL,
  PRIMARY KEY (`knjiga_id_knjiga`, `autor_id_autor`),
  INDEX `fk_Autor_knjige_Autor1_idx` (`autor_id_autor` ASC),
  CONSTRAINT `fk_Autor_knjige_Knjiga1`
    FOREIGN KEY (`knjiga_id_knjiga`)
    REFERENCES `id11622579_mybook_db`.`knjiga` (`id_knjiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_knjige_Autor1`
    FOREIGN KEY (`autor_id_autor`)
    REFERENCES `id11622579_mybook_db`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id11622579_mybook_db`.`zanr_knjige`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id11622579_mybook_db`.`zanr_knjige` (
  `zanr_id_zanr` INT NOT NULL,
  `knjiga_id_knjiga` INT NOT NULL,
  PRIMARY KEY (`zanr_id_zanr`, `knjiga_id_knjiga`),
  INDEX `fk_Zanr_knjige_Knjiga1_idx` (`knjiga_id_knjiga` ASC),
  CONSTRAINT `fk_Zanr_knjige_Zanr1`
    FOREIGN KEY (`zanr_id_zanr`)
    REFERENCES `id11622579_mybook_db`.`zanr` (`id_zanr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zanr_knjige_Knjiga1`
    FOREIGN KEY (`knjiga_id_knjiga`)
    REFERENCES `id11622579_mybook_db`.`knjiga` (`id_knjiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
